/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const ICountry = t.iface([], {
  "countryCode": "string",
  "countryInternationalName": "string",
  "countryLocalName": t.opt("string"),
});

export const ISpec = t.iface([], {
  "films": t.array("IFilm"),
  "tvShows": t.array("ITelevisionShow"),
});

export const IFilm = t.iface([], {
  "name": "string",
  "countries": t.array("ICountry"),
});

export const ITelevisionShow = t.iface([], {
  "title": "string",
  "countries": t.array("ICountry"),
  "series": t.array("ISeries"),
});

export const ISeries = t.iface([], {
  "seriesNumber": "number",
  "year": "number",
  "episodes": t.array("IEpisode"),
});

export const IEpisode = t.iface([], {
  "episodeNumber": "number",
  "date": "string",
  "actors": t.array("IActor"),
});

export const IActor = t.iface([], {
  "stageName": "string",
  "realName": "string",
});

const exportedTypeSuite = {
  ICountry,
  ISpec,
  IFilm,
  ITelevisionShow,
  ISeries,
  IEpisode,
  IActor,
};
export default exportedTypeSuite;
